### ISSUE TITLE
Message carbons are not logged to chat log file

### ISSUE THREAD

**Issue by janteau** [profanity-im/profanity#1181]
## Expected Behavior

In the chat logs messages sent from Profanity along with messages sent by other clients (carbons) should be logged into the log file.
## Current Behavior

Chat logs contain messages received and messages sent by the Profanity client, but do not include messages sent by the user's other clients.  I am using OMEMO encryption in the chats that I experience this behavior (/omemo log on is enabled).
## Steps to Reproduce (for bugs)

1. Turn on chat logging.
2. Log into account through Profanity and another client at the same time.
3. Send messages from Profanity as well as another client.
4. Messages sent by other client are present in window.
5. Inspect chat logs for current conversation.

## Environment

Profanity, version 0.7.0

Build information:
XMPP library: libmesode
Desktop notification support: Disabled
OTR support: Disabled
PGP support: Disabled
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (2.7.15+)
GTK icons: Disabled

System: Ubuntu Linux 18.04

glib2.0 Version: 2.56.4-0ubuntu0.18.04.4

**Comment by jubalh** [comment]
Code doesnt log carbons indeed.
Also in carbon case we dont make sure that message->plain is always set.

Will fix this when I have time.

**Comment by jubalh** [comment]
@janteau please try again with latest master.

Seems like MUC logging is totally broken too. Funny noone noticed it :-)
I'll adress this in a seperate issue.

Logging of carbons (on 1:1) should now work.

**Comment by janteau** [comment]
@jubalh This still doesn't seem to work for me.  I did a git pull from master this evening as you can see from the version number below.  Messages sent by me using profanity to users on my roster are logged, but the messages sent from Conversations are not logged (but do show on the screen).

Enabling and disabling OMEMO made no difference.

Version 0.7.0dev.master.09b6fc9a

**Comment by jubalh** [comment]
@mdosch can you also test this once you find time?

**Comment by mdosch** [comment]
I just had a quick look at my logfiles:

* 1-1
    * A 1-1 message (OMEMO encrypted) sent by another client (Conversations) is not showing up, there is even no logfile for that day.
    * A message sent by profanity creates the logfile and shows up in the log
* MUC
    * A message sent by profanity is appearing in the log twice
    * A message sent by conversations is appearing in the log once
    * MUC PM sent by conversations or profanity don't show up
    * MUC PM received is logged twice (one time as sent by me and one time as received from the contact)

So it seems logging is broken. Any special use cases you like to be tested?

```
profanity --version
Profanity, version 0.7.0dev.master.09b6fc9a
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.13.1-unknown)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (2.7.16+)
GTK icons: Enabled
```

**Comment by jubalh** [comment]
Trying to have a look soon. Thanks for the feedback guys!

**Comment by janteau** [comment]
@jubalh I took a look at my log files over the past couple of days, and it appears messages from my Gajim client were also not logged.

**Comment by jubalh** [comment]
Gosh. There is a lot of stuff wrong here I think.
Findings so far:

In `src/xmpp/message.c` we have message handlers, like `_handle_carbons` and `_private_chat_handler` etc.
We make sure that message->plain is set there. If it's not we set it from message->body.

Later in `src/event/server_events.c` we have `_sv_ev_incoming_plain` which takes care of incoming messages on a higher level. Printing them to the window and logging it to a file.

There we have `if (message->body) { ... message->plain = strdup(message->body)...}` so it could be that we assigned the correct value to plain and now overwrite it.

Also we use `chatwin_incoming_msg()` in `_sv_ev_incoming_plain` for logging the message. But it could be that it needs to be logged as an outgoing message in case of a carbon.

**Comment by jubalh** [comment]
@janteau please test with latest master and give feedback here.

**Comment by janteau** [comment]
@jubalh I started testing this tonight.  It seems to be working so far.  Messages sent from my other client (Conversations) seem to be appearing in my logs now.  I will comment again if I find something not working with this. Thanks!

Unrelated I think, I did find a message that appeared in Profanity from a contact that did not get logged into the log file (while I was testing).  I can't reproduce it (the following messages were logged).  If I can find how to reproduce it, I'll open a separate issue report.

**Comment by janteau** [comment]
@jubalh Maybe this is expected, but my carbons are still not logged in MUCs.  Seems to be working for 1-1 chats.

**Comment by jubalh** [comment]
@weiss is it possible that messages to a MUC from another client are not also sent via Carbons?
So the only way to get them is MUC reflection?

@janteau this is a new bug then, introduced by https://github.com/profanity-im/profanity/commit/147be3afdfd2f87e989450bf0cddddfa9e817e24.
Where I stop logging incoming MUC messages when they come from our own nick.

I do this because we log the message already as an outgoing MUC message here: https://github.com/profanity-im/profanity/blob/master/src/event/client_events.c#L346

We log the outgoing one so we have an easier time with OMEMO.

**Comment by jubalh** [comment]
So when receiving incoming MUC messages I have no way to know if it was sent from the current client or another one..

**Comment by jubalh** [comment]
@paulfariello is it OMEMO wise possible to stop logging outgoing MUC messages and only log incoming ones?
Users have to trust their own keys for that to work, I guess.
We still know whether its OMEMO encrypted or not, so we can move the 'redact' logic to the incoming part only.

In this case we could remove outgoing logging and just log incoming stuff.

**Comment by weiss** [comment]
> So when receiving incoming MUC messages I have no way to know if it was sent from the current client or another one..

You could add an [origin ID][1] to track your own messages.  (Or just the normal message ID, but old servers might mess with that: XEP-0045 didn't [require MUC services to maintain the original message ID][2] until revision 1.31 from 2018.)

[1]: https://xmpp.org/extensions/xep-0359.html#origin-id
[2]: https://xmpp.org/extensions/xep-0045.html#message

**Comment by jubalh** [comment]
I'll close this issue and reopen https://github.com/profanity-im/profanity/issues/1201 instead.
Since this issue is actually closed but the fix in 1201 is not correct in case one uses multiple clients in MUC.

**Comment by janteau** [comment]
@jubalh This seems to be working!  Thanks!  My 1:1 received messages do not seem to get logged now, not sure if it's related.  I therefore opened a new issue #1214.
